---
ip: "192.168.10.10"
memory: 2048
cpus: 1
hostname: tomatocart
name: tomatocart
provider: virtualbox
box: 'hashicorp/precise64'

authorize: ~/.ssh/id_rsa.pub

mysqlrootpass: tomatocart

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "/Users/jackyin/Documents/workspace/tomatocart/TomatoCart-v1"
      to: "/var/www/tomatocart-v1"
      owner: "vagrant"
      group: "www-data"

sites:
    - map: "tocv1" 
      to: "/var/www/tomatocart-v1"

databases:
    - tomatocart 

# ports:
#     - send: 93000
#       to: 9300
#     - send: 7777
#       to: 777
#       protocol: udp
